##################################################################################################
## 
##  Xilinx, Inc. 2010            www.xilinx.com 
##  Sat Feb 27 15:06:27 2021

##  Generated by MIG Version 4.2
##  
##################################################################################################
##  File name :       example_top.xdc
##  Details :     Constraints file
##                    FPGA Family:       ARTIX7
##                    FPGA Part:         XC7A200T-FBG484
##                    Speedgrade:        -1
##                    Design Entry:      VERILOG
##                    Frequency:         325.19999999999999 MHz
##                    Time Period:       3075 ps
##################################################################################################

##################################################################################################
## Controller 0
## Memory Device: DDR3_SDRAM->SODIMMs->MT8KTF51264HZ-1G9
## Data Width: 64
## Time Period: 3075
## Data Mask: 0
##################################################################################################
############## NET - IOSTANDARD ##################



set_property INTERNAL_VREF  0.750 [get_iobanks 14]
set_property INTERNAL_VREF  0.750 [get_iobanks 15]
set_property INTERNAL_VREF  0.750 [get_iobanks 16]