# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/ethan/Documents/GitHub/Big-Crete-Calculator/Digital-Designs/Template/Template.srcs/sources_1/ip/mipi_csi2_rx_subsystem_0/mipi_csi2_rx_subsystem_0.xci
# IP: The module: 'mipi_csi2_rx_subsystem_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/ethan/Documents/GitHub/Big-Crete-Calculator/Digital-Designs/Template/Template.srcs/sources_1/ip/mipi_csi2_rx_subsystem_0/bd_0/bd_639e_0.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_639e_0 || ORIG_REF_NAME==bd_639e_0} -quiet] -quiet

# IP: c:/Users/ethan/Documents/GitHub/Big-Crete-Calculator/Digital-Designs/Template/Template.srcs/sources_1/ip/mipi_csi2_rx_subsystem_0/bd_0/ip/ip_0/bd_639e_0_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_639e_0_xbar_0 || ORIG_REF_NAME==bd_639e_0_xbar_0} -quiet] -quiet

# IP: c:/Users/ethan/Documents/GitHub/Big-Crete-Calculator/Digital-Designs/Template/Template.srcs/sources_1/ip/mipi_csi2_rx_subsystem_0/bd_0/ip/ip_1/bd_639e_0_r_sync_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_639e_0_r_sync_0 || ORIG_REF_NAME==bd_639e_0_r_sync_0} -quiet] -quiet

# IP: c:/Users/ethan/Documents/GitHub/Big-Crete-Calculator/Digital-Designs/Template/Template.srcs/sources_1/ip/mipi_csi2_rx_subsystem_0/bd_0/ip/ip_2/bd_639e_0_rx_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_639e_0_rx_0 || ORIG_REF_NAME==bd_639e_0_rx_0} -quiet] -quiet

# IP: c:/Users/ethan/Documents/GitHub/Big-Crete-Calculator/Digital-Designs/Template/Template.srcs/sources_1/ip/mipi_csi2_rx_subsystem_0/bd_0/ip/ip_3/bd_639e_0_phy_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_639e_0_phy_0 || ORIG_REF_NAME==bd_639e_0_phy_0} -quiet] -quiet

# IP: c:/Users/ethan/Documents/GitHub/Big-Crete-Calculator/Digital-Designs/Template/Template.srcs/sources_1/ip/mipi_csi2_rx_subsystem_0/bd_0/ip/ip_4/bd_639e_0_vfb_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_639e_0_vfb_0_0 || ORIG_REF_NAME==bd_639e_0_vfb_0_0} -quiet] -quiet

# XDC: c:/Users/ethan/Documents/GitHub/Big-Crete-Calculator/Digital-Designs/Template/Template.srcs/sources_1/ip/mipi_csi2_rx_subsystem_0/bd_0/bd_639e_0_ooc.xdc

# XDC: c:/Users/ethan/Documents/GitHub/Big-Crete-Calculator/Digital-Designs/Template/Template.srcs/sources_1/ip/mipi_csi2_rx_subsystem_0/mipi_csi2_rx_subsystem_0_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'mipi_csi2_rx_subsystem_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/ethan/Documents/GitHub/Big-Crete-Calculator/Digital-Designs/Template/Template.srcs/sources_1/ip/mipi_csi2_rx_subsystem_0/mipi_csi2_rx_subsystem_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mipi_csi2_rx_subsystem_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/ethan/Documents/GitHub/Big-Crete-Calculator/Digital-Designs/Template/Template.srcs/sources_1/ip/mipi_csi2_rx_subsystem_0/mipi_csi2_rx_subsystem_0_fixed_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mipi_csi2_rx_subsystem_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/ethan/Documents/GitHub/Big-Crete-Calculator/Digital-Designs/Template/Template.srcs/sources_1/ip/mipi_csi2_rx_subsystem_0/mipi_csi2_rx_subsystem_0.xci
# IP: The module: 'mipi_csi2_rx_subsystem_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/ethan/Documents/GitHub/Big-Crete-Calculator/Digital-Designs/Template/Template.srcs/sources_1/ip/mipi_csi2_rx_subsystem_0/bd_0/bd_639e_0.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_639e_0 || ORIG_REF_NAME==bd_639e_0} -quiet] -quiet

# IP: c:/Users/ethan/Documents/GitHub/Big-Crete-Calculator/Digital-Designs/Template/Template.srcs/sources_1/ip/mipi_csi2_rx_subsystem_0/bd_0/ip/ip_0/bd_639e_0_xbar_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_639e_0_xbar_0 || ORIG_REF_NAME==bd_639e_0_xbar_0} -quiet] -quiet

# IP: c:/Users/ethan/Documents/GitHub/Big-Crete-Calculator/Digital-Designs/Template/Template.srcs/sources_1/ip/mipi_csi2_rx_subsystem_0/bd_0/ip/ip_1/bd_639e_0_r_sync_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_639e_0_r_sync_0 || ORIG_REF_NAME==bd_639e_0_r_sync_0} -quiet] -quiet

# IP: c:/Users/ethan/Documents/GitHub/Big-Crete-Calculator/Digital-Designs/Template/Template.srcs/sources_1/ip/mipi_csi2_rx_subsystem_0/bd_0/ip/ip_2/bd_639e_0_rx_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_639e_0_rx_0 || ORIG_REF_NAME==bd_639e_0_rx_0} -quiet] -quiet

# IP: c:/Users/ethan/Documents/GitHub/Big-Crete-Calculator/Digital-Designs/Template/Template.srcs/sources_1/ip/mipi_csi2_rx_subsystem_0/bd_0/ip/ip_3/bd_639e_0_phy_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_639e_0_phy_0 || ORIG_REF_NAME==bd_639e_0_phy_0} -quiet] -quiet

# IP: c:/Users/ethan/Documents/GitHub/Big-Crete-Calculator/Digital-Designs/Template/Template.srcs/sources_1/ip/mipi_csi2_rx_subsystem_0/bd_0/ip/ip_4/bd_639e_0_vfb_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_639e_0_vfb_0_0 || ORIG_REF_NAME==bd_639e_0_vfb_0_0} -quiet] -quiet

# XDC: c:/Users/ethan/Documents/GitHub/Big-Crete-Calculator/Digital-Designs/Template/Template.srcs/sources_1/ip/mipi_csi2_rx_subsystem_0/bd_0/bd_639e_0_ooc.xdc

# XDC: c:/Users/ethan/Documents/GitHub/Big-Crete-Calculator/Digital-Designs/Template/Template.srcs/sources_1/ip/mipi_csi2_rx_subsystem_0/mipi_csi2_rx_subsystem_0_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'mipi_csi2_rx_subsystem_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/ethan/Documents/GitHub/Big-Crete-Calculator/Digital-Designs/Template/Template.srcs/sources_1/ip/mipi_csi2_rx_subsystem_0/mipi_csi2_rx_subsystem_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mipi_csi2_rx_subsystem_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/ethan/Documents/GitHub/Big-Crete-Calculator/Digital-Designs/Template/Template.srcs/sources_1/ip/mipi_csi2_rx_subsystem_0/mipi_csi2_rx_subsystem_0_fixed_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mipi_csi2_rx_subsystem_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
