##################################################################################################
## 
##  Xilinx, Inc. 2010            www.xilinx.com 
##  Thu Jul  8 21:51:47 2021

##  Generated by MIG Version 4.2
##  
##################################################################################################
##  File name :       example_top.sd
##  Details :     Constraints file
##                    FPGA Family:       ARTIX7
##                    FPGA Part:         XC7A200TIFBG484_PKG
##                    Speedgrade:        -1
##                    Design Entry:      VERILOG
##                    Frequency:         324.68000000000001 MHz
##                    Time Period:       3080 ps
##################################################################################################

##################################################################################################
## Controller 0
## Memory Device: DDR3_SDRAM->SODIMMs->CMSO4GX3M1C1600C11
## Data Width: 64
## Time Period: 3080
## Data Mask: 0
##################################################################################################

set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_ck_n[*]} ]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_ck_p[*]} ]
          
#create_clock -period 3.08 [get_ports sys_clk_i]
          
############## NET - IOSTANDARD ##################



set_property INTERNAL_VREF  0.750 [get_iobanks 14]
set_property INTERNAL_VREF  0.750 [get_iobanks 15]
set_property INTERNAL_VREF  0.750 [get_iobanks 16]