###################################################################################################
## This constraints file contains default clock frequencies to be used during creation of a 
## Synthesis Design Checkpoint (DCP). For best results the frequencies should be modified 
## to match the target frequencies. 
## This constraints file is not used in top-down/global synthesis (not the default flow of Vivado).
###################################################################################################


##################################################################################################
## 
##  Xilinx, Inc. 2010            www.xilinx.com 
##  Thu Jul  8 22:12:55 2021

##  Generated by MIG Version 4.2
##  
##################################################################################################
##  File name :       RamBuf.xdc
##  Details :     Constraints file
##                    FPGA Family:       ARTIX7
##                    FPGA Part:         XC7A200T-FBG484
##                    Speedgrade:        -2
##                    Design Entry:      VERILOG
##                    Frequency:         324.68000000000001 MHz
##                    Time Period:       3080 ps
##################################################################################################

##################################################################################################
## Controller 0
## Memory Device: DDR3_SDRAM->SODIMMs->CMSO4GX3M1C1600C11
## Data Width: 64
## Time Period: 3080
## Data Mask: 0
##################################################################################################

create_clock -period 3.08 [get_ports sys_clk_i]
          