##################################################################################################
## 
##  Xilinx, Inc. 2010            www.xilinx.com 
##  Fri Sep 29 12:58:00 2023

##  Generated by MIG Version 4.2
##  
##################################################################################################
##  File name :       example_top.xdc
##  Details :     Constraints file
##                    FPGA Family:       ARTIX7
##                    FPGA Part:         XC7A200T-SBG484
##                    Speedgrade:        -1
##                    Design Entry:      VERILOG
##                    Frequency:         333.32999999999998 MHz
##                    Time Period:       3000 ps
##################################################################################################

##################################################################################################
## Controller 0
## Memory Device: DDR3_SDRAM->SODIMMs->MT16KTF1G64HZ-1G6
## Data Width: 64
## Time Period: 3000
## Data Mask: 0
##################################################################################################
############## NET - IOSTANDARD ##################



set_property INTERNAL_VREF  0.750 [get_iobanks 14]
set_property INTERNAL_VREF  0.750 [get_iobanks 15]
set_property INTERNAL_VREF  0.750 [get_iobanks 16]